config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  namespace :admin do
    get 'search' => 'searches#search'
    get 'contacts/checker' => 'contacts#checker', as: 'checker'
    resources :users, only: [:index, :show, :edit, :update]
    resources :tweets, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show, :update]
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }

  scope module: :public do
    get 'tweets/thanks' => 'tweets#thanks', as: 'thanks'
    get 'search' => 'searches#search'
    get '/tweet/hashtag/:name' => "tweets#hashtag"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :tweets, only: [:new, :index, :show, :create] do
      resource :likes, only: [:create, :destroy]
    end
  end

  root to: 'homes#top'
  get 'about' => 'homes#about', as: 'about'
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm' =>  'contacts#confirm', as: 'confirm'
  post 'contacts/back' => 'contacts#back', as: 'back'
  get 'done' => 'contacts#done', as: 'done'



end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { normal: 0, report: 1, other: 2 }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :name, presence: true
  # validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  # validates :message, presence: true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :tweet_hashtag_relations, dependent: :destroy
  has_many :tweets, through: :tweet_hashtag_relations, dependent: :destroy
  validates :hashname, presence: true, length: { maximum:10 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :tweet_hashtag_relations, dependent: :destroy
  has_many :hashtags, through: :tweet_hashtag_relations, dependent: :destroy
  
  validates :tweet, presence: true, length: { maximum: 140 }
  validate :tweets_count_must_be_within_limit
  validate :tweets_count_one_day_limit

  after_create do
    tweet = Tweet.find_by(id: self.id)
    hashtags = self.tweet.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tweet.hashtags = []
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      tweet.hashtags << tag
    end
  end

  def favorited_by?(user)
    likes.exists?(user_id: user.id)
  end

  private

  def tweets_count_must_be_within_limit
    errors.add(:base, "投稿は七回までです") if user.tweets.count >= 7
  end

  def tweets_count_one_day_limit
    # byebug
    errors.add(:base, "本日は投稿できません") if user.tweets.length > 0 && user.tweets.last.created_at.day == Date.today.day && user.tweets.last.created_at.month == Date.today.month && user.tweets.last.created_at.year == Date.today.year
  end
end

app/models/tweet_hashtag_relation.rb
class TweetHashtagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :hashtag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 10 }
  validates :introduction, length: { maximum: 50 }
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image_square.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
    followings.include?(user)
  end

end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    @word = params[:words]
    @range = params[:range]
    if @range == "User"
      @users = User.where("name LIKE(?)", "%#{params[:words]}%").page(params[:page]).per(10)
    elsif @range == "Tweet"
      @tweets = Tweet.where("tweet LIKE(?)", "%#{params[:words]}%").page(params[:page]).per(10)
    else
      @contacts = Contact.where("message LIKE(?)", "%#{params[:words]}%").page(params[:page]).per(10)
    end
  end
end

app/controllers/admin/tweets_controller.rb
class Admin::TweetsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tweets = Tweet.page(params[:page]).per(10)
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to admin_tweets_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :twitter, :instagram, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end


  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  def done
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :subject, :message)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
    @tweets = Tweet.all.sample(8)
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/tweets_helper.rb
module Admin::TweetsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/searches/_search.html.erb
<br>
<div class="search_form">
  <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
    <div class="d-flex justify-content-end">
      <%= f.text_field :words, class: 'form-control col-md-6 col-sm-10' %>
    </div>
    <div class="d-flex justify-content-end">
      <%= f.select :range, options_for_select([['ユーザー','User'], ['投稿','Tweet'], ['お問い合わせ','Contact']]), {}, class: 'form-control col-md-3 col-sm-4' %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
<br>

app/views/admin/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-12 order-bottom">
      <h5 class="mt-4 font-weight-bold">"<%= @word %>"検索結果</h5>
      <% if @range == "User" %>
        <% if @users.present? %>
          <table class="table">
            <tr>
              <th>名前</th>
              <th></th>
            </tr>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to admin_user_path(user) do %>
                    <%= user.name %>
                  <% end %>
                </td>
                <td></td>
              </tr>
            <% end %>
          </table>
          <%= paginate @users %>
        <% else %>
          <h2>対象のユーザーはいません</h2>
        <% end %>
      <% elsif @range == "Tweet" %>
        <% if @tweets.present? %>
          <table class="table">
            <tr>
              <th>ユーザーネーム</th>
              <th>投稿内容</th>
            </tr>
            <% @tweets.each do |tweet| %>
            <tr>
              <td><%= tweet.user.name %></td>
              <td>
                <%= link_to admin_tweet_path(tweet) do %>
                  <%= tweet.tweet.truncate(30) %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </table>
          <%= paginate @tweets %>
        <% else %>
          <h2>対象の投稿はありません</h2>
        <% end %>
      <% else %>
        <% if @contacts.present? %>
          <table class="table">
            <tr>
              <th>名前</th>
              <th>お問い合わせ内容</th>
            </tr>
             <% @contacts.each do |contact| %>
              <tr>
                <td><%= contact.name %></td>
                <td>
                  <%= link_to admin_contact_path(contact) do %>
                    <%= contact.message.truncate(20) %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
          <%= paginate @contacts %>
        <% else %>
          <h2>対象のお問い合わせはありません</h2>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-12 order-top">
      <br>
      <div class="search_form">
        <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
          <div class="d-flex justify-content-end">
            <%= f.text_field :words, class: 'form-control' %>
          </div>
          <div class="d-flex justify-content-end">
            <%= f.select :range, options_for_select([['ユーザー','User'], ['投稿','Tweet'], ['お問い合わせ','Contact']]), {}, class: 'form-control' %>
            <%= f.submit "検索", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <br>
    </div>
  </div>
</div>