config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  namespace :admin do
    get 'search' => 'searches#search'
    get 'contacts/checker' => 'contacts#checker', as: 'checker'
    resources :users, only: [:index, :show, :edit, :update]
    resources :tweets, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show, :update]
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }

  scope module: :public do
    get 'tweets/thanks' => 'tweets#thanks', as: 'thanks'
    get 'search' => 'searches#search'
    get '/tweet/hashtag/:name' => "tweets#hashtag"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :tweets, only: [:new, :index, :show, :create] do
      resource :likes, only: [:create, :destroy]
    end
  end

  root to: 'homes#top'
  get 'about' => 'homes#about', as: 'about'
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm' =>  'contacts#confirm', as: 'confirm'
  post 'contacts/back' => 'contacts#back', as: 'back'
  get 'done' => 'contacts#done', as: 'done'



end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { normal: 0, report: 1, other: 2 }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :name, presence: true
  # validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  # validates :message, presence: true
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @contacts = Contact.page(params[:page]).per(10)
    @contact_normal = Contact.where(subject: 'normal').page(params[:page]).per(10)
    @contact_report = Contact.where(subject: 'report').page(params[:page]).per(10)
    @contact_other = Contact.where(subject: 'other').page(params[:page]).per(10)
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
  end
  
  def checker
    @contact_check = Contact.where(check: false).page(params[:page])
    @contact_normal = Contact.where(subject: 'normal').page(params[:page]).per(10)
    @contact_report = Contact.where(subject: 'report').page(params[:page]).per(10)
    @contact_other = Contact.where(subject: 'other').page(params[:page]).per(10)
  end

  private

  def contact_params
    params.require(:contact).permit(:check)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end


  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  def done
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :subject, :message)
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admin/contacts/_check.html.erb
<% if contact.check == true %>
  <%= link_to admin_contact_path(contact.id, contact: {check: false}), remote: true, method: :patch do %>
    <i class="fas fa-check-square"></i>
  <% end %>
<% else %>
  <%= link_to admin_contact_path(contact.id, contact: {check: true}), remote: true, method: :patch do %>
    <i class="far fa-square"></i>
  <% end %>
<% end %>

app/views/admin/contacts/_list.html.erb
<table class="table">
  <tr>
    <th>
      <%= link_to 'チェック', admin_checker_path %>
    </th>
    <th>投稿者</th>
    <th>ご用件</th>
    <th>内容</th>
  </tr>
  <% contacts.each do |contact| %>
  <tr>
    <td class="check_btn_<%= contact.id %>">
      <%= render 'admin/contacts/check', contact: contact %>
    </td>
    <td><%= contact.name %></td>
    <td><%= contact.subject_i18n %></td>
    <td>
      <%= link_to admin_contact_path(contact) do %>
        <%= contact.message.truncate(10) %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/contacts/checker.html.erb
<div class="container">
  <div class="row d-flex justify-content-around">
    <div class="col-md-10 col-sm-12">
      <%= render 'admin/searches/search' %>
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to 'すべて', '#all', 'data-toggle': 'tab', class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to '通常のお問い合わせ', '#normal', 'data-toggle': 'tab', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to '通報', '#report', 'data-toggle': 'tab', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'その他', '#other', 'data-toggle': 'tab', class: 'nav-link' %>
        </li>
      </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="all"><%= render 'admin/contacts/list', contacts: @contact_check %></div>
          <div class="tab-pane" id="normal"><%= render 'admin/contacts/list', contacts: @contact_normal %></div>
          <div class="tab-pane" id="report"><%= render 'admin/contacts/list', contacts: @contact_report %></div>
          <div class="tab-pane" id="other"><%= render 'admin/contacts/list', contacts: @contact_other %></div>
        </div>
      <%= paginate @contact_check %>
    </div>
  </div>
</div>

app/views/admin/contacts/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-around">
    <div class="col-md-10 col-sm-12">
      <%= render 'admin/searches/search' %>
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to 'すべて', '#all', 'data-toggle': 'tab', class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to '通常のお問い合わせ', '#normal', 'data-toggle': 'tab', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to '通報', '#report', 'data-toggle': 'tab', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'その他', '#other', 'data-toggle': 'tab', class: 'nav-link' %>
        </li>
      </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="all"><%= render 'admin/contacts/list', contacts: @contacts %></div>
          <div class="tab-pane" id="normal"><%= render 'admin/contacts/list', contacts: @contact_normal %></div>
          <div class="tab-pane" id="report"><%= render 'admin/contacts/list', contacts: @contact_report %></div>
          <div class="tab-pane" id="other"><%= render 'admin/contacts/list', contacts: @contact_other %></div>
        </div>
      <%= paginate @contacts %>
    </div>
  </div>
</div>

app/views/admin/contacts/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-around">
    <div class="col-md-8 col-sm-12">
      <table class="table mt-5">
        <tr>
          <th>名前</th>
          <td><%= @contact.name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @contact.email %></td>
        </tr>
        <tr>
          <th>日付</th>
          <td><%= @contact.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>ご用件</th>
          <td>
            <%= @contact.subject_i18n %>
          </td>
        </tr>
        <tr>
          <th>内容</th>
          <td class="break-word">
            <span id="check_btn_<%= @contact.id %>">
              <%= render 'admin/contacts/check', contact: @contact %>
            </span>
            <%= @contact.message %>
          </td>
        </tr>
      </table>
      <%= link_to '戻る', admin_contacts_path %>
    </div>
  </div>
</div>

app/views/admin/contacts/update.js.erb
$('.check_btn_<%= @contact.id %>').html("<%= j(render "admin/contacts/check", contact: @contact) %>");