config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  namespace :admin do
    get 'search' => 'searches#search'
    get 'contacts/checker' => 'contacts#checker', as: 'checker'
    resources :users, only: [:index, :show, :edit, :update]
    resources :tweets, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show, :update]
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }

  scope module: :public do
    get 'tweets/thanks' => 'tweets#thanks', as: 'thanks'
    get 'search' => 'searches#search'
    get '/tweet/hashtag/:name' => "tweets#hashtag"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :tweets, only: [:new, :index, :show, :create] do
      resource :likes, only: [:create, :destroy]
    end
  end

  root to: 'homes#top'
  get 'about' => 'homes#about', as: 'about'
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm' =>  'contacts#confirm', as: 'confirm'
  post 'contacts/back' => 'contacts#back', as: 'back'
  get 'done' => 'contacts#done', as: 'done'



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 10 }
  validates :introduction, length: { maximum: 50 }
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image_square.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
    followings.include?(user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :twitter, :instagram, :is_active)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-around">
    <div class="col-6">
      <%= form_with model: @user, url: admin_user_path(@user) do |f| %>
        <br>
        <div class="edit-page">
          <%= f.label :name, '名前' %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="edit-page">
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        <div class="edit-page">
          <%= f.label :twitter, 'Twitter' %>
          <%= f.text_field :twitter, class: "form-control" %>
        </div>
        <div class="edit-page">
          <%= f.label :instagram, 'Instagram' %>
          <%= f.text_field :instagram, class: "form-control" %>
        </div>
        <div class="edit-page">
          <%= f.label :introduction, '自己紹介' %>
          <%= f.text_area :introduction, rows:'7', class: "form-control" %>
        </div>
        <div class="edit-page">
          <%= f.radio_button :is_active, true %><%= f.label :is_active, "有効", class: "text-active" %>
          <%= f.radio_button :is_active, false %><%= f.label :is_active, "退会済み", class: "text-invalid" %>
        </div>
        <div class="edit-btn">
          <%= f.submit '更新', class: "btn btn-outline-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-around">
    <div class="col-md-10 col-sm-12">
      <%= render 'admin/searches/search' %>
      <table class="table mt-5">
        <tr>
          <th>名前</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to admin_user_path(user) do %>
                <%= user.name %>
              <% end %>
            </td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_active? %>
                <span class="text-success">有効</span>
              <% else %>
                <span class="text-secondary">退会済み</span>
              <% end %>
                </span>
            </td>
          </tr>
        <% end %>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-around">
    <div class="col-10">
      <table class="table mt-5">
        <tr>
          <th>名前</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>メール</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>Twitter</th>
          <td><%= @user.twitter %></td>
        </tr>
        <tr>
          <th>Instagram</th>
          <td><%= @user.instagram %></td>
        </tr>
        <tr>
          <th>自己紹介</th>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @user.is_active? %>
              <span class="text-success">有効</span>
            <% else %>
              <span class="text-secondary">退会済み</span>
            <% end %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td><%= link_to '編集', edit_admin_user_path(@user), class: "btn btn-outline-success edit-btn" %></td>
        </tr>
      </table>
      <table class="table">
        <tr>
          <th>投稿</th>
          <th>日付</th>
          <td></td>
        </tr>
        <% @tweets.each do |tweet| %>
          <tr>
            <td>
              <%= link_to admin_tweet_path(tweet) do %>
                <%= tweet.tweet.truncate(10) %>
              <% end %>
            </td>
            <td><%= tweet.created_at.strftime('%Y/%m/%d') %></td>
            <td></td>
          </tr>
        <% end %>
      </table>
      <div class="m-3"><%= link_to '戻る', admin_users_path %></div>
    </div>
  </div>
</div>