config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  namespace :admin do
    get 'search' => 'searches#search'
    get 'contacts/checker' => 'contacts#checker', as: 'checker'
    resources :users, only: [:index, :show, :edit, :update]
    resources :tweets, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show, :update]
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions",
  }

  scope module: :public do
    get 'tweets/thanks' => 'tweets#thanks', as: 'thanks'
    get 'search' => 'searches#search'
    get '/tweet/hashtag/:name' => "tweets#hashtag"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :tweets, only: [:new, :index, :show, :create] do
      resource :likes, only: [:create, :destroy]
    end
  end

  root to: 'homes#top'
  get 'about' => 'homes#about', as: 'about'
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm' =>  'contacts#confirm', as: 'confirm'
  post 'contacts/back' => 'contacts#back', as: 'back'
  get 'done' => 'contacts#done', as: 'done'



end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { normal: 0, report: 1, other: 2 }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :name, presence: true
  # validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  # validates :message, presence: true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :tweet_hashtag_relations, dependent: :destroy
  has_many :tweets, through: :tweet_hashtag_relations, dependent: :destroy
  validates :hashname, presence: true, length: { maximum:10 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :tweet_hashtag_relations, dependent: :destroy
  has_many :hashtags, through: :tweet_hashtag_relations, dependent: :destroy
  
  validates :tweet, presence: true, length: { maximum: 140 }
  validate :tweets_count_must_be_within_limit
  validate :tweets_count_one_day_limit

  after_create do
    tweet = Tweet.find_by(id: self.id)
    hashtags = self.tweet.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tweet.hashtags = []
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      tweet.hashtags << tag
    end
  end

  def favorited_by?(user)
    likes.exists?(user_id: user.id)
  end

  private

  def tweets_count_must_be_within_limit
    errors.add(:base, "投稿は七回までです") if user.tweets.count >= 7
  end

  def tweets_count_one_day_limit
    # byebug
    errors.add(:base, "本日は投稿できません") if user.tweets.length > 0 && user.tweets.last.created_at.day == Date.today.day && user.tweets.last.created_at.month == Date.today.month && user.tweets.last.created_at.year == Date.today.year
  end
end

app/models/tweet_hashtag_relation.rb
class TweetHashtagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :hashtag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 10 }
  validates :introduction, length: { maximum: 50 }
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image_square.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def followings?(user)
    followings.include?(user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :twitter, :instagram, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end


  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  def done
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :subject, :message)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
    @tweets = Tweet.all.sample(8)
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/tweets_helper.rb
module Admin::TweetsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <ul class="p-0 list-unstyled">
      <% obj.errors.full_messages.each do |message| %>
        <li class="alert alert-danger"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="head-color text-white pt-5 pb-4">
  <div class="container">
    <div class="row">
      <div class="col">
        <h6 class="text-dark text-center">お問い合わせは</h6>
        <ul class="p-0 list-unstyled">
          <li class="text-center">
            <i class="fab fa-telegram"></i>
            <%= link_to 'コチラ', new_contact_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm head-color">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <div class="navbar-brand p-3">
        <%= link_to root_path do %>
          <div class="logo-image"></div>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to user_path(current_user) do %>
                <div class="nav-link text-dark"><i class="fas fa-user mr-1 ml-1"></i>マイページ</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to tweets_path do %>
                <div class="nav-link text-dark"><i class="fas fa-crown mr-1 ml-1"></i>ランキング</div>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_tweet_path do %>
                <div class="nav-link text-dark"><i class="fas fa-envelope mr-1 ml-1"></i>投稿</div>
              <% end %>
            </li>
          </ul>
        </div>
      <% elsif admin_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", admin_tweets_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "お問い合わせ一覧", admin_contacts_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "Cicadaとは", about_path(anchor: 'about_menu'), class: 'nav-link text-dark' %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seven</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>

</html>